packages:
  #
  # Assets
  #
  - small-asset

  #
  # Utility functions for tests
  #
  - test-utils/docker-images
  - test-utils/guided-command
  - test-utils/hello-world
  - test-utils/hello-world-py
  - test-utils/java-stub
  - test-utils/python-stub
  - test-utils/read-with-sleep
  - test-utils/runenv-java-stub
  - test-utils/runenv-python-stub

  #
  # Production CLI instruments for use in workflows
  #
  - sleep
  - table-converter
  - mnz-client

  - catalogue
  - catalogue-tests

catalog:
  'turbo': ^2.3.3
  '@changesets/cli': ^2.27.10

  "@platforma-sdk/package-builder": "^3.11.0"
  "@platforma-sdk/blocks-deps-updater": "^2.0.0"
  "@platforma-open/milaboratories.runenv-python-3": "^1.7.5"
