name: Build NPM package
on:
  push:
    branches:
      - 'main'
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
      - id: pkg_version
        uses: milaboratory/github-ci/actions/helpers/jq@v4
        with:
          file: "./package.json"
          select: '.version'
  run:
    needs:
      - init
    uses: milaboratory/github-ci-internal/.github/workflows/node-go-simple.yaml@v4
    with:
      app-name: Small cross-platform utils
      app-name-slug: 'small-cross-platform-packages'
      notify-telegram: true
      node-version: '20.x'
      golang-version: '1.22'
      is-electron-application: 'false'
      always-auth: 'true'
      build-script-name: 'build'
      test: true
      test-script-name: 'test'
      registry-url: 'https://registry.npmjs.org'
      scope: '@platforma-open'
      publish-to-public: true
      npmrc-config: |
        {
          "registries": {
            "https://registry.npmjs.org/": {
              "scopes": ["milaboratories", "platforma-sdk", "platforma-open"],
              "tokenVar": "NPMJS_TOKEN"
            },
            "https://npm.pkg.github.com/": {
              "scopes": ["milaboratory"],
              "tokenVar": "NODE_AUTH_TOKEN"
            }
          }
        }
      env: >-
        {
          "PL_REGISTRY_PLATFORMA_OPEN_UPLOAD_URL": "s3://milab-euce1-prod-pkgs-s3-platforma-registry/pub/?region=eu-central-1"
        }
      aws-publish-enable: true
      aws-iam-role-to-assume: 'arn:aws:iam::511903394050:role/milab-euce1-prod-github-oidc-role-pl-registry'
    secrets:
      env: |
        {
          "NPMJS_TOKEN": ${{ toJSON(secrets.NPMJS_TOKEN) }}
        }
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT_CLASSIC_BLOCKS }}
