name: Build NPM package
on:
  push:
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main

      - id: pkg_version
        uses: milaboratory/github-ci/actions/helpers/jq@v4
        with:
          file: "./package.json"
          select: '.version'

    outputs:
      version: ${{ steps.pkg_version.outputs.value }}

  run:
    needs:
      - init

    uses: milaboratory/github-ci-internal/.github/workflows/node-go-simple.yaml@v4
    with:
      env: >
        { "GO_BUILD_VERSION": "${{ needs.init.outputs.version }}" }
      app-name: Small cross-platform utils
      app-name-slug: 'small-cross-platform-packages'
      notify-telegram: true

      node-version: '20.x'
      golang-version: '1.22'
      is-electron-application: 'false'
      always-auth: 'true'

      build-script-name: 'build'

      test: false
      test-script-name: 'test'

      publish-script-name: 'release'

    secrets:
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT_CLASSIC_BLOCKS }}
