name: Build and Test NPM packages
on:
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/node-simple-pnpm.yaml@v4-beta
    with:
      app-name: Small cross-platform utils
      app-name-slug: 'small-cross-platform-packages'
      notify-telegram: true
      node-version: '20.x'
      golang-version: '1.22'
      build-script-name: 'build'

      test: true
      test-script-name: 'test'
      publish-to-public: true

      pnpm-recursive-build: false
      pnpm-recursive-tests: false
      npmrc-config: |
        {
          "registries": {
            "https://registry.npmjs.org/": {
              "scopes": ["milaboratories", "platforma-open", "platforma-sdk"],
              "tokenVar": "NPMJS_TOKEN"
            },
            "https://npm.pkg.github.com/": {
              "scopes": ["milaboratory"],
              "tokenVar": "NODE_AUTH_TOKEN"
            }
          }
        }
    secrets:
      env: |
        { "PL_REGISTRY_PLATFORMA_OPEN_UPLOAD_URL": ${{ toJSON(secrets.PL_REGISTRY_PLOPEN_UPLOAD_URL) }},
          "NPMJS_TOKEN": ${{ toJSON(secrets.NPMJS_TOKEN) }},
          "AWS_CI_IAM_MONOREPO_SIMPLE_ROLE": ${{ toJSON(secrets.AWS_CI_IAM_MONOREPO_SIMPLE_ROLE) }},
          "AWS_CI_TURBOREPO_S3_BUCKET": ${{ toJSON(secrets.AWS_CI_TURBOREPO_US_S3_BUCKET) }} }

      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}

      GH_ZEN_APP_ID: ${{ secrets.GH_ZEN_APP_ID }}
      GH_ZEN_APP_PRIVATE_KEY: ${{ secrets.GH_ZEN_APP_PRIVATE_KEY }}
