name: Build NPM package
on:
  push:
    branches:
      - 'main'
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
      - id: pkg_version
        uses: milaboratory/github-ci/actions/helpers/jq@v4
        with:
          file: "./package.json"
          select: '.version'
  run:
    needs:
      - init
    uses: milaboratory/github-ci/.github/workflows/node-go-simple.yaml@v4-beta
    with:
      app-name: Small cross-platform utils
      app-name-slug: 'small-cross-platform-packages'
      notify-telegram: true
      node-version: '20.x'
      golang-version: '1.22'
      is-electron-application: 'false'
      always-auth: 'true'
      build-script-name: 'build'
      test: true
      test-script-name: 'test'
      publish-to-public: true
      aws-login-enable: true
      gcp-login-enable: true
      registry-url: 'https://registry.npmjs.org/'
      npmrc-config: |
        {
          "registries": {
            "https://registry.npmjs.org/": {
              "scopes": ["platforma-open"],
              "tokenVar": "NPMJS_TOKEN"
            }
          }
        }
    secrets:
      env: |
        {
          "NPMJS_TOKEN": ${{ toJSON(secrets.NPMJS_TOKEN) }},
          "GH_CI_PAT": "${{ toJSON(secrets.GH_PAT_CLASSIC_BLOCK) }}",
          "PL_REGISTRY_PLATFORMA_OPEN_UPLOAD_URL": ${{ toJSON(secrets.PL_REGISTRY_PLOPEN_UPLOAD_URL) }}
        }
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}

      AWS_ASSUME_ROLE: ${{ secrets.AWS_CI_IAM_MONOREPO_SIMPLE_ROLE }}
      AWS_ASSUME_REGION: 'eu-central-1'

      GCP_KMS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCLOUD_KMS_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_KMS_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_KMS_SERVICE_ACCOUNT }}
      GCP_KMS_LOCATION: ${{ secrets.GCLOUD_KMS_LOCATION }}
      GCP_KMS_KEYRING: ${{ secrets.GCLOUD_KMS_KEYRING }}
      GCP_KMS_KEY_NAME: ${{ secrets.GCLOUD_KMS_KEY_NAME }}
